name: Java CI

on:
    push:
        branches:
            - master

jobs:
    build-test-format:
        runs-on: ubuntu-latest

        steps:
            - name: Repository auschecken
              uses: actions/checkout@v4

            - name: Java 25 installieren
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 25

            - name: Projekt bauen
              run: ./gradlew build
              working-directory: app

            - name: Tests ausführen
              run: ./gradlew test
              working-directory: app

            - name: Formatierung prüfen
              run: ./gradlew spotlessCheck
              working-directory: app
